###############################################################################
# Exploratory Nearshore Respirometry R Script #
# Code adapted from Nate S, UFloridasee package `respR`                       #
# Created by AO and OP on Oct 11, 2020 #
# Automate Respirometry-Related Data. https://github.com/januarharianto/respr,#

rm(list = ls())

#install.packages("devtools")
#devtools::install_github("januarharianto/respR")
#library(respR)
lapply(c("tidyr", "plyr", "dplyr", "ggplot2", "magrittr", "respR",
         "lubridate", "knitr", "tidyverse", "reshape2", "RcppRoll", "readr"), 
       library, character.only = T)
library(tidyverse)

setwd("~/Repository/nearshore-respirometry")



#Potential Framework

#1. open csv for sample1 and corresponding bg csv

#2. apply function1 : slices df in two 
# based on first 30 minutes, dark treatment (500 rows from the start) 
# and the last 30 minutes, light treatment (500 rows from the end)

#3. apply function2 : inspects all 4 chunks for errors
#(sample1_dark, sample1_light, bg_dark, bg_light)

#4. apply function3 : calculates rates for both treatment by 
# a. calculating bg rate for dark, 
# b. calculating bg rate for light,
# c. calculating sample rate for dark,
# d. calculates sample rate for light, 
# e. subtracts sample rate by bg rate for dark,
# f. subtracts sample rate by bg rate for light

#5. apply function4 : converts final rates for light and dark based on metadata volumes

#6. create loop to autofill metadata dataframe with outputs....?





################################################################
################ Long version for troubleshooting ##############
################################################################
##1. 
metadata <- read_csv("metadata_OP.csv")
S01_M3_002 <- read.csv("kelp_2020_resp_O2_files/S01_M3_002.csv", 
                      skip = 1,
                      header = TRUE)
# read csv and skips extra top row generated by the import from presens
S01_C <- read.csv("kelp_2020_resp_O2_files/S01_C.csv",
                  skip = 1,
                  header = TRUE)
#S01_M3_002$delta_t <- as.numeric(as.character(S01_M3_002$delta_t))
#S01_C$delta_t <- as.numeric(as.character(S01_C$delta_t))

##2. 

S01_M3_002_dark <- subset(S01_M3_002, delta_t >5 & delta_t <30)
S01_M3_002_light <- top_n(S01_M3_002, 500, delta_t)
  #subset(S01_M3_002.rd, time >35)


#separates dark and light treatment - sample data
S01_C_dark <- subset(S01_C, delta_t >5 & delta_t <30)
S01_C_light <- top_n(S01_C, 500, delta_t)
#separates dark and light treatment - bg data


##3.
insp_S01_M3_002_dark <- inspect(S01_M3_002_dark, time = 7, oxygen = 9)
insp_S01_M3_002_dark
insp_S01_M3_002_light <- inspect(S01_M3_002_light, time = 7, oxygen = 9)
insp_S01_M3_002_light


insp_S01_C_dark <- inspect(S01_C_dark, time = 7, oxygen = 9)
insp_S01_C_dark
insp_S01_C_light <- inspect(S01_C_light, time = 7, oxygen = 9)
insp_S01_C_light

##4.
rate_S01_M3_002_dark <- auto_rate(insp_S01_M3_002_dark)
rate_S01_M3_002_dark

rate_S01_M3_002_light <- auto_rate(insp_S01_M3_002_light)
rate_S01_M3_002_light

rate_S01_C_dark <- calc_rate.bg(insp_S01_C_dark)
rate_S01_C_dark
#rate_S01_C_dark1 <- auto_rate(insp_S01_C_dark)
#rate_S01_C_dark1
##### doesn't output same results....? extra step in the calc_rate.bg function...?

rate_S01_C_light <- calc_rate.bg(insp_S01_C_light)
rate_S01_C_light
#rate_S01_C_light1 <- auto_rate(insp_S01_C_light)
#rate_S01_C_light1
##### same as above...

adj_rate_S01_M3_002_dark <- adjust_rate(rate_S01_M3_002_dark, rate_S01_C_dark) #subtraction
adj_rate_S01_M3_002_dark
adj_rate_S01_M3_002_light <- adjust_rate(rate_S01_M3_002_light, rate_S01_C_light)
adj_rate_S01_M3_002_light

##5. 
V01_M3_002 <- metadata %>%
  filter(sampleID == "S01_M3_002")

convrt_rate_S01_M3_002_dark <- convert_rate(adj_rate_S01_M3_002_dark, 
             o2.unit = "mg/L", 
             time.unit = "min", 
             output.unit = "mg/h/g", 
             volume = ((V01_M3_002$volume_chamber - V01_M3_002$volume_kelp)/1000),# in Liters,
             mass = V01_M3_002$wet_weight_g/1000)# in kg 
convrt_rate_S01_M3_002_dark

convrt_rate_S01_M3_002_light <- convert_rate(adj_rate_S01_M3_002_light, 
                     o2.unit = "mg/L", 
                     time.unit = "min", 
                     output.unit = "mg/h/g", 
                     volume = (V01_M3_002$volume_chamber/1000 - V01_M3_002$volume_kelp/1000), 
                     mass = V01_M3_002$wet_weight_g/1000) 
convrt_rate_S01_M3_002_light


################################################################
################# Function for bulk application ################
################################################################

my_fun  <- function(file_name){
  
  file <- read.csv(paste0("kelp_2020_resp_O2_files/", file_list[[1]]),
                    skip = 1,#ignore first row
                    header = TRUE)
  
  #subsets, inspects and calculates O2 rate for sample chamber under dark condition 
  sample_dark <- file %>%
    subset(delta_t >5 & delta_t <30) %>% # trims first 5 minutes off the first 30 minutes of the run
    inspect(time = 7, oxygen = 9)%>% # inspects for large anomalies in data
    auto_rate() # generates 5 rates based on most linear parts of data
  
  #subsets, inspects and calculates O2 rate for sample chamber under light condition 
  sample_light <- file %>%
    top_n(500, delta_t)%>%
    inspect(time = 7, oxygen = 9)%>%
    auto_rate()
} 
  #converts results into a df
  df_dark <- as.data.frame(sample_dark$summary[1])
  df_dark$sampleID <- deparse(substitute(file))
  df_dark$treatment <- "dark"
  
  df_light <- as.data.frame(sample_light$summary[1])
  df_light$sampleID <- deparse(substitute(file))
  df_light$treatment <- "light"
  
  df <- rbind(df_light, df_dark)
  
  # do stuff
#  if(file$sample_type == "background"){
   # do backgroundstuff to give output
#  } else {
    # do  otherstuff to give output
#  }
  
#  #do more generic stuff
  
#  return(output)
}

metadata <- read_csv("metadata_OP.csv")

file_list <- list.files("kelp_2020_resp_O2_files")


dataframe <- ldply(file_list, my_fun)#%>%
  #left_join(metadata, by = sampleID)

  str(dataframe)
     
  
 