###############################################################################
# Exploratory Nearshore Respirometry R Script #
# Code adapted from Nate S, UFloridasee package `respR`                       #
# Created by AO and OP on Oct 11, 2020 #
# Automate Respirometry-Related Data. https://github.com/januarharianto/respr,#

rm(list = ls())

#install.packages("devtools")
#devtools::install_github("januarharianto/respR")
#library(respR)
lapply(c("tidyr", "plyr", "dplyr", "ggplot2", "magrittr", "respR",
         "lubridate", "knitr", "tidyverse", "reshape2", "RcppRoll", "readr"), 
       library, character.only = T)
library(tidyverse)

setwd("~/Repository/nearshore-respirometry") # Ondine

#Framework

#1. open csv for sample1 and corresponding bg csv

#2. slices df in two 
# based on first 30 minutes, dark treatment (500 rows from the start) 
# and the last 30 minutes, light treatment (500 rows from the end)

#3. inspects all 4 chunks for errors
#(sample1_dark, sample1_light, bg_dark, bg_light)

#4. calculate O2rates based on most linear segments by: 
# a. calculating bg rate for dark, 
# b. calculating bg rate for light,
# c. calculating sample rate for dark,
# d. calculates sample rate for light, 
# e. subtracts sample rate by bg rate for dark,
# f. subtracts sample rate by bg rate for light

#5. converts final rates for light and dark 
# based on sample metadata volumes and weights

###############################################################
################ Long version for troubleshooting #############
###############################################################
##1. 
metadata <- read_csv("metadata_OP.csv")
S01_M3_002 <- read.csv("kelp_2020_resp_O2_files/S01_M3_002.csv", 
                      skip = 1,
                      header = TRUE)
# read csv and skips extra top row generated by the import from presens
S01_C <- read.csv("kelp_2020_resp_O2_files/S01_C.csv",
                  skip = 1,
                  header = TRUE)
#S01_M3_002$delta_t <- as.numeric(as.character(S01_M3_002$delta_t))
#S01_C$delta_t <- as.numeric(as.character(S01_C$delta_t))

##2. 

S01_M3_002_dark <- subset(S01_M3_002, delta_t >5 & delta_t <30)
S01_M3_002_light <- top_n(S01_M3_002, 500, delta_t)
  #subset(S01_M3_002.rd, time >35)


#separates dark and light treatment - sample data
S01_C_dark <- subset(S01_C, delta_t >5 & delta_t <30)
S01_C_light <- top_n(S01_C, 500, delta_t)
#separates dark and light treatment - bg data


##3.
insp_S01_M3_002_dark <- inspect(S01_M3_002_dark, time = 7, oxygen = 9)
insp_S01_M3_002_dark
insp_S01_M3_002_light <- inspect(S01_M3_002_light, time = 7, oxygen = 9)
insp_S01_M3_002_light


insp_S01_C_dark <- inspect(S01_C_dark, time = 7, oxygen = 9)
insp_S01_C_dark
insp_S01_C_light <- inspect(S01_C_light, time = 7, oxygen = 9)
insp_S01_C_light

##4.
rate_S01_M3_002_dark <- auto_rate(insp_S01_M3_002_dark)
rate_S01_M3_002_dark

rate_S01_M3_002_light <- auto_rate(insp_S01_M3_002_light)
rate_S01_M3_002_light

rate_S01_C_dark <- calc_rate.bg(insp_S01_C_dark)
rate_S01_C_dark
rate_S01_C_dark1 <- auto_rate(insp_S01_C_dark)
rate_S01_C_dark1
##### doesn't output same results....? extra step in the calc_rate.bg function...?

rate_S01_C_light <- calc_rate.bg(insp_S01_C_light)
rate_S01_C_light
rate_S01_C_light1 <- auto_rate(insp_S01_C_light)
rate_S01_C_light1

adj_rate_S01_M3_002_dark <- adjust_rate(rate_S01_M3_002_dark, rate_S01_C_dark) #subtraction
adj_rate_S01_M3_002_dark
adj_rate_S01_M3_002_light <- adjust_rate(rate_S01_M3_002_light, rate_S01_C_light)
adj_rate_S01_M3_002_light 

##5. 
V01_M3_002 <- metadata %>%
  filter(sampleID == "S01_M3_002")

convrt_rate_S01_M3_002_dark <- convert_rate(adj_rate_S01_M3_002_dark, 
             o2.unit = "mg/L", 
             time.unit = "min", 
             output.unit = "mg/h/g", 
             volume = ((V01_M3_002$volume_chamber - V01_M3_002$volume_kelp)/1000),# in Liters,
             mass = V01_M3_002$wet_weight_g/1000)# in kg 
convrt_rate_S01_M3_002_dark

convrt_rate_S01_M3_002_light <- convert_rate(adj_rate_S01_M3_002_light, 
                     o2.unit = "mg/L", 
                     time.unit = "min", 
                     output.unit = "mg/h/g", 
                     volume = (V01_M3_002$volume_chamber/1000 - V01_M3_002$volume_kelp/1000), 
                     mass = V01_M3_002$wet_weight_g/1000) 
convrt_rate_S01_M3_002_light

df_convrt_rate_S01_M3_002_light <- as.data.frame(convrt_rate_S01_M3_002_light$summary[2])
df_convrt_rate_S01_M3_002_light$sampleID <- deparse(substitute(S01_M3_002))
df_convrt_rate_S01_M3_002_light$treatment <- "light"


df_convrt_rate_S01_M3_002_dark <- as.data.frame(convrt_rate_S01_M3_002_dark$summary[2])
df_convrt_rate_S01_M3_002_dark$sampleID <- deparse(substitute(S01_M3_002))
df_convrt_rate_S01_M3_002_dark$treatment <- "dark"

df_convrt_rates <- rbind(df_convrt_rate_S01_M3_002_light, df_convrt_rate_S01_M3_002_dark)
                            

################################################################
################# Function for bulk application ################
################################################################

my_fun  <- function(file_name){
  
  file <- read.csv(paste0("kelp_2020_resp_O2_files/", file_name[[1]]),
                    skip = 1,#ignore first row
                    header = TRUE)

  #subsets, inspects and calculates O2 rate for sample chamber under dark condition 
  sample_dark <- file %>%
    subset(delta_t >5 & delta_t <30) %>% # trims first 5 minutes off the first 30 minutes of the run
    inspect(time = 7, oxygen = 9)%>% # inspects for large anomalies in data
    auto_rate() # generates 5 rates based on most linear parts of data
  
  #subsets, inspects and calculates O2 rate for sample chamber under light condition 
  sample_light <- file %>%
    top_n(500, delta_t)%>%
    inspect(time = 7, oxygen = 9)%>%
    auto_rate()
 
  #converts results into a df
  df_dark <- as.data.frame(sample_dark$summary[1])
  df_dark$sampleID <- gsub(".csv","",file_name) 
  df_dark$treatment <- "dark"
  
  df_light <- as.data.frame(sample_light$summary[1])
  df_light$sampleID <- gsub(".csv","",file_name)
  df_light$treatment <- "light"
  
  df <- rbind(df_light, df_dark)
  
# consider alternative function where 
# bgs are calculated using calc_rate.bg instead of auto_rate...?
  
#  if(file$sample_type == "background"){
   # do backgroundstuff to give output
#  } else {
    # do  otherstuff to give output
#  }
#  return(output)
}

metadata <- read_csv("metadata_OP.csv")

file_list <- list.files("kelp_2020_resp_O2_files")

dataframe <- ldply(file_list, my_fun)%>%
left_join(metadata, dataframe, by = "sampleID")




# subtract background signal from samples O2rates based on trial ID and treatment
dataframe_bg <- dataframe %>%
  select(rate_b1, sample_type, trialID, treatment) %>% 
  subset(sample_type == "background") %>%
  rename(rate_bg = rate_b1)
dataframe_spl <- dataframe %>%
  subset(sample_type == "sample") %>%
  rename(rate_spl = rate_b1)
data <- left_join(dataframe_spl, dataframe_bg, by = c("trialID", "treatment"))
data$rate_adj <- data$rate_spl - data$rate_bg #seems backgrounds are very low!!!

# converts rates of O2 based on sample and chamber volumes as well as sample weight
data$rate_convrt <- data$rate_adj * 
  ((data$volume_chamber - data$volume_kelp)/1000)*
  (1/data$wet_weight_g)*
  60
  #convert_rate(data$rate_adj,
  #                        o2.unit = "mg/L", 
  #                        time.unit = "min", 
  #                        output.unit = "mg/h/g", 
  #                        volume = ((data$volume_chamber - data$volume_kelp)/1000),# in Liters,
  #                        mass = data$wet_weight_g/1000)# in kg 
data$rate_convrt_units <- "mg/h/g"    

write.csv(data, "kelp_2020_data.csv") 


#### ZOSTERA ###
setwd("~/nearshore-respirometry") # Ang

# ----- Long version for troubleshooting ------------#
## Step 1. Read in data

# Metadata
metadata <- read_csv("metadata_AMO.csv")

# Experimental Chamber
# read csv and skips extra top row generated by the import from presens
z005_O2 <- read.csv("zostera_o2_files/z005_O2.csv", 
                       skip = 1, 
                       header = TRUE)
# Background Chamber
# read csv and skips extra top row generated by the import from presens
z007_02_BG <- read.csv("zostera_o2_files/z007_O2.csv",
                  skip = 1,
                  header = TRUE)

#S01_M3_002$delta_t <- as.numeric(as.character(S01_M3_002$delta_t))
#S01_C$delta_t <- as.numeric(as.character(S01_C$delta_t))

## Step 2. Parse each chamber into dataframes: dark and light 

z005_O2_dark <- subset(z005_O2, delta_t >5 & delta_t <30)
z005_O2_light <- top_n(z005_O2, 500, delta_t)
#subset(S01_M3_002.rd, time >35)


#separates dark and light treatment - sample data
z007_02_BG_dark <- subset(z007_02_BG, delta_t >5 & delta_t <30)
z007_02_BG_light <- top_n(z007_02_BG, 500, delta_t)
#separates dark and light treatment - bg data


##3.
insp_z005_O2_dark <- inspect(z005_O2_dark, time = 7, oxygen = 9)
insp_z005_O2_dark
insp_z005_O2_light <- inspect(z005_O2_light, time = 7, oxygen = 9)
insp_z005_O2_light


insp_z007_02_BG_dark <- inspect(z007_02_BG_dark, time = 7, oxygen = 9)
insp_z007_02_BG_dark
insp_z007_02_BG_light <- inspect(z007_02_BG_light, time = 7, oxygen = 9)
insp_z007_02_BG_light

##4.
rate_z005_O2_dark <- auto_rate(insp_z005_O2_dark)
rate_z005_O2_dark
rate_z005_O2_light <- auto_rate(insp_z005_O2_light)
rate_z005_O2_light

rate_z007_02_BG_dark <- calc_rate.bg(insp_z007_02_BG_dark)
rate_z007_02_BG_dark
rate_z007_02_BG_dark1 <- auto_rate(insp_z007_02_BG_dark)
rate_z007_02_BG_dark1
##### doesn't output same results....? extra step in the calc_rate.bg function...?

rate_z007_02_BG_light <- calc_rate.bg(insp_z007_02_BG_light)
rate_z007_02_BG_ight
rate_z007_02_BG_light1 <- auto_rate(insp_z007_02_BG_light)
rate_z007_02_BG_light1

adj_rate_z005_O2_dark <- adjust_rate(rate_z005_O2_dark, rate_z007_02_BG_dark) #subtraction
adj_rate_z005_O2_dark
adj_rate_z005_O2_light <- adjust_rate(rate_z005_O2_light, rate_z007_02_BG_light)
adj_rate_z005_O2_light 

##5. 
V01_M3_002 <- metadata %>%
  filter(sampleID == "z005")

convrt_rate_z005_O2_dark <- convert_rate(adj_rate_z005_O2_dark, 
                                            o2.unit = "mg/L", 
                                            time.unit = "min", 
                                            output.unit = "mg/h/g", 
                                            volume = ((V01_M3_002$volume_chamber - V01_M3_002$volume_kelp)/1000),# in Liters,
                                            mass = V01_M3_002$wet_weight_g/1000)# in kg 
convrt_rate_z005_O2_dark

convrt_rate_z005_O2_light <- convert_rate(adj_rate_z005_O2_light, 
                                             o2.unit = "mg/L", 
                                             time.unit = "min", 
                                             output.unit = "mg/h/g", 
                                             volume = (V01_M3_002$volume_chamber/1000 - V01_M3_002$volume_kelp/1000), 
                                             mass = V01_M3_002$wet_weight_g/1000) 
convrt_rate_z005_O2_light

df_convrt_rate_z005_O2_light <- as.data.frame(convrt_rate_z005_O2_light$summary[2])
df_convrt_rate_z005_O2_light$sampleID <- deparse(substitute(z005))
df_convrt_rate_z005_O2_light$treatment <- "light"


df_convrt_rate_z005_02_dark <- as.data.frame(convrt_rate_z005_O2_dark$summary[2])
df_convrt_rate_z005_02_dark$sampleID <- deparse(substitute(z005))
df_convrt_rate_z005_02_dark$treatment <- "dark"

df_convrt_rates <- rbind(df_convrt_rate_z005_O2_light, df_convrt_rate_z005_02_dark)
df_convrt_rates 

################################################################
################# Function for bulk application ################
################################################################

my_fun  <- function(file_name){
  
  file <- read.csv(paste0("kelp_2020_resp_O2_files/", file_name[[1]]),
                   skip = 1,#ignore first row
                   header = TRUE)
  
  #subsets, inspects and calculates O2 rate for sample chamber under dark condition 
  sample_dark <- file %>%
    subset(delta_t >5 & delta_t <30) %>% # trims first 5 minutes off the first 30 minutes of the run
    inspect(time = 7, oxygen = 9)%>% # inspects for large anomalies in data
    auto_rate() # generates 5 rates based on most linear parts of data
  
  #subsets, inspects and calculates O2 rate for sample chamber under light condition 
  sample_light <- file %>%
    top_n(500, delta_t)%>%
    inspect(time = 7, oxygen = 9)%>%
    auto_rate()
  
  #converts results into a df
  df_dark <- as.data.frame(sample_dark$summary[1])
  df_dark$sampleID <- gsub(".csv","",file_name) 
  df_dark$treatment <- "dark"
  
  df_light <- as.data.frame(sample_light$summary[1])
  df_light$sampleID <- gsub(".csv","",file_name)
  df_light$treatment <- "light"
  
  df <- rbind(df_light, df_dark)
  
  # consider alternative function where 
  # bgs are calculated using calc_rate.bg instead of auto_rate...?
  
  #  if(file$sample_type == "background"){
  # do backgroundstuff to give output
  #  } else {
  # do  otherstuff to give output
  #  }
  #  return(output)
}

metadata <- read_csv("metadata_OP.csv")

file_list <- list.files("kelp_2020_resp_O2_files")

dataframe <- ldply(file_list, my_fun)%>%
  left_join(metadata, dataframe, by = "sampleID")




# subtract background signal from samples O2rates based on trial ID and treatment
dataframe_bg <- dataframe %>%
  select(rate_b1, sample_type, trialID, treatment) %>% 
  subset(sample_type == "background") %>%
  rename(rate_bg = rate_b1)
dataframe_spl <- dataframe %>%
  subset(sample_type == "sample") %>%
  rename(rate_spl = rate_b1)
data <- left_join(dataframe_spl, dataframe_bg, by = c("trialID", "treatment"))
data$rate_adj <- data$rate_spl - data$rate_bg #seems backgrounds are very low!!!

# converts rates of O2 based on sample and chamber volumes as well as sample weight
data$rate_convrt <- data$rate_adj * 
  ((data$volume_chamber - data$volume_kelp)/1000)*
  (1/data$wet_weight_g)*
  60
#convert_rate(data$rate_adj,
#                        o2.unit = "mg/L", 
#                        time.unit = "min", 
#                        output.unit = "mg/h/g", 
#                        volume = ((data$volume_chamber - data$volume_kelp)/1000),# in Liters,
#                        mass = data$wet_weight_g/1000)# in kg 
data$rate_convrt_units <- "mg/h/g"    

write.csv(data, "kelp_2020_data.csv")  
 